# Linear Algebra
1. Tensors
2. Matrix mul
3. Indentity and inverse
4. Linear dependence and span
5. Norms
6. Special kinds of of Matrices
7. Engendecomposition
8. Singular value decomposition
9. Moore-Penrose
10. Trace Operator
11. Determinant
12. Principal componenet analysis

In [19]:
import numpy as np
from numpy.linalg import inv

## 1. Tensors
Array of multiple axes. array of numbers arranged on a regular grid with variable number of axes. denoted as **A**

In [3]:
# transpose mirror image along main diagonal
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# 2. Matrix Multiplication
* C=AB
* Cij = Aik, Bkj
* Distributive A(B+C) = AB +AC
* Not Commutative AB != BA
* Transpose commutative = A.T * B == B.T * A

In [13]:
A = np.arange(10).reshape(2,5)
B = np.arange(10).reshape(5,2)
C = np.matmul(A,B)
D = np.matmul(B,A)
C, D

(array([[ 60,  70],
        [160, 195]]), array([[  5,   6,   7,   8,   9],
        [ 15,  20,  25,  30,  35],
        [ 25,  34,  43,  52,  61],
        [ 35,  48,  61,  74,  87],
        [ 45,  62,  79,  96, 113]]))

In [16]:
A = np.arange(16).reshape(4,4)
B = np.arange(16).reshape(4,4)
np.matmul(A.T, B) == np.matmul(B.T, A)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [21]:
inv(A)

array([[  9.00719925e+14,  -4.50359963e+14,  -1.80143985e+15,
          1.35107989e+15],
       [ -2.40191980e+15,   2.70215978e+15,   1.80143985e+15,
         -2.10167983e+15],
       [  2.10167983e+15,  -4.05323966e+15,   1.80143985e+15,
          1.50119988e+14],
       [ -6.00479950e+14,   1.80143985e+15,  -1.80143985e+15,
          6.00479950e+14]])

In [22]:
np.matmul(A, inv(A))

array([[ 1.,  0.,  0.,  0.],
       [ 0., -2.,  1., -2.],
       [ 2.,  0., -2., -4.],
       [ 0.,  0.,  0., -2.]])

# Identity and Inverse Matrices
* matrix inversion allow us to analytically solve linear equations
* Identity matrix - matrix with diagonal 1's
* 