In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot = True)

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [2]:
n_nodes_hl1 = 500
n_nodes_hl2 = 500
n_nodes_hl3 = 500
n_classes = 10
batch_size = 100

In [3]:
x = tf.placeholder('float', [None, 784])
y = tf.placeholder('float')

In [25]:
def neural_network(data):
    weights1 = tf.Variable(tf.random_normal([784, n_nodes_hl1]))
    bias1 = tf.Variable(tf.random_normal([n_nodes_hl1]))
    
    weights2 = tf.Variable(tf.random_normal([n_nodes_hl1, n_nodes_hl2]))
    bias2 = tf.Variable(tf.random_normal([n_nodes_hl2]))
    
    weights3 = tf.Variable(tf.random_normal([n_nodes_hl2, n_nodes_hl3]))
    bias3 = tf.Variable(tf.random_normal([n_nodes_hl3]))
    
    weights_out = tf.Variable(tf.random_normal([n_nodes_hl3, n_classes]))
    bias_out = tf.Variable(tf.random_normal([n_classes]))
    
    layer1 = tf.add(tf.matmul(data, weights1), bias1)
    layer1 = tf.nn.relu(layer1)
    
    layer2 = tf.add(tf.matmul(layer1, weights2), bias2)
    layer2 = tf.nn.relu(layer2)
    
    layer3 = tf.add(tf.matmul(layer2, weights3), bias3)
    layer3 = tf.nn.relu(layer3)
    
    layer_out = tf.add(tf.matmul(layer3, weights_out),bias_out)
    
    return layer_out

In [19]:
def train_nn(x):
    prediction = neural_network(x)
    # difference between prediction and known labels
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=y))
    
    # AdamOptimizer is like SGD -  learning rate defaults as 0.001
    optimizer = tf.train.AdamOptimizer().minimize(cost)
    
    # cycles of feedforward and backproping weights
    hm_epochs = 10
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        
        for epoch in range(hm_epochs):
            epoch_loss = 0
            
            for _ in range(int(mnist.train.num_examples/batch_size)):
                # data , labels
                epoch_x, epoch_y = mnist.train.next_batch(batch_size)
                _, c = sess.run([optimizer, cost], feed_dict={x:epoch_x, y:epoch_y})
                epoch_loss += c
            print('Epoch', epoch, 'completed out of', hm_epochs, 'loss', epoch_loss)
        
        # hoping that the hone hots are the same
        correct = tf.equal(tf.argmax(prediction,1 ), tf.argmax(y, 1))
        
        # cast correct to a float and this is the accuracy
        accuracy = tf.reduce_mean(tf.cast(correct, 'float'))
        print('Accuracy', accuracy.eval({x:mnist.test.images, y:mnist.test.labels}))

In [20]:
train_nn(x)

Epoch 0 completed out of 10 loss 1974877.21759
Epoch 1 completed out of 10 loss 413722.918957
Epoch 2 completed out of 10 loss 227079.632043
Epoch 3 completed out of 10 loss 132923.453069
Epoch 4 completed out of 10 loss 80562.2044011
Epoch 5 completed out of 10 loss 51550.9421525
Epoch 6 completed out of 10 loss 34063.4316802
Epoch 7 completed out of 10 loss 25666.4059559
Epoch 8 completed out of 10 loss 19054.1953
Epoch 9 completed out of 10 loss 16344.1521182
Accuracy 0.9531


In [24]:
import numpy as np
a = np.arange(100)
batch_size = 20
start = 0
stop = batch_size
for i in range(len(a)//batch_size):
    print(a[start:stop])
    start +=batch_size
    stop+=batch_size

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
[80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
